?start: whole_sentence
whole_sentence: sentence END_POINT
    | whole_sentence whole_sentence
sentence: np rel_clause? vp
np: DET? CARD? ORD? QUANT? ap? NOUN
    | np COORD np
rel_clause: REL_WORD sentence
vp: VERB np?
    | vp COORD vp
ap: ADJ
    | ap ap
    | ap COORD ap

%declare COORD
%declare NOUN
%declare REL_WORD
%declare DET
%declare VERB
%declare END_POINT
%declare QUANT
%declare ADJ
%declare ORD
%declare CARD

%import common.WS
%ignore WS
